### ISSUE TITLE
(T) Нарушение требований ТЗ

### ISSUE THREAD

**Issue by ikit-mita** [ytnytn1/homework1#1]
Креатив это хорошо, но надо придерживаться ТЗ
1. Убрать ограничения на возраст - моя электронная кошка может быть стара, как мамонт
1. Убрать убийство - гринписа на тебя нет, пусть здоровье в минус уходит
1. Откуда ограничение на максимальное здоровье? Убрать
1. Цвет должен вводиться пользователем - я хочу кошку цветом Гималайский закат/Перуанский прибой
1. Здоровье не должно выводиться - по ТЗ это вообще внутренний параметр кошки, наружу только цвет торчит

**Comment by ytnytn1** [comment]
Исправил
